#!/usr/bin/env bash
#script that display bad luck in 4th loop and good luck in 8th loop
i=0
while [ $i -lt 10 ]
do
(( i++ ))
if [ $i -eq 4 ]
then
echo "bad luck"
elif [ $i -eq 8 ]
then
echo "good luck"
else
echo "Holberton School"
fi
done
