#!/usr/bin/env bash
#script that display bad luck from Chine in 4th loop, good luck from Japan in 9th loop, and bad luck from Italy in 17th loop
i=1
while [ $i -le 20 ]
do
echo $i
case $i in
4)
echo "bad luck from China"
;;
9)
echo "bad luck from Japan"
;;
17)
echo "bad luck from Italy"
;;
esac
((i++))
done
